### ISSUE TITLE
Hallownest's Crown / Transition Randomizer broken logic

### ISSUE THREAD

**Issue by kevingandrews** [homothetyhk/RandomizerMod#20]
When using transition randomizer, starting at Hallownest's Crown and walking off the left side to the falling transition immediately places everything you encounter through that transition out of logic.

I'm unfamiliar with your code base, but [this](https://github.com/homothetyhk/RandomizerMod/blob/13c8931012aed35f7900d03eb6a60c558c68bff6/RandomizerMod/Resources/Data/starts.json#L176), specifically the (tuple I think) transition looks to not account for anything except exiting through the bottom.

**Comment by flibber-hk** [comment]
The explanation of how that works is that only the listed transition (in this case `Mines_34[bot1]`) is marked as being reachable (except for things which are reachable from that transition). For the same reason, the pale ore check will not be in logic until you can get there from the transition. (As for why [bot1] was chosen instead of [bot2], that would be because you can get to [bot2] from [bot1] with some movement later, so it's sligtly more useful.)

The reason for this behaviour (i.e. only getting a single transition as guaranteed progression) is mainly historical, as the technology to add more things to logic from a start location was not added until fairly recently. That said, this is only a type 2 logic error, so it won't stop seeds from being completable.

**Comment by homothetyhk** [comment]
Fixed in [5e99a28](https://github.com/homothetyhk/RandomizerMod/commit/5e99a28326b55908b586db492c82716911c0cd74).
