### ISSUE TITLE
Additional Platforms missing from certain areas

### ISSUE THREAD

**Issue by ChrysAlice** [homothetyhk/RandomizerMod#30]
There are certain areas where it's still possible to softlock yourself with Additional Platforms turned on, requiring a save-and-quit or benchwarp.

There are three I've run into specifically:

1. The first fight with Hornet in Greenpath leads to a dead end.  If the player has no movement options, there is no way to leave.
2. The screen just outside the City Storerooms stag has an area to the left of the descent where the player can drop down, fight a couple of enemies and get a check.  Without movement options there is no way to get back out.
3. The Shape of Unn check can be reached using only Isma's Tear, but cannot be escaped without at least one mantis claw.

**Comment by BadMagic100** [comment]
Fwiw, that setting is not intended to completely prevent any softlocks. The added platforms are conveniences intended to prevent prohibitively long walks back to the same place, and benchwarp usage is still expected.

Notably for 1 and 3 those are cases where the platforms aren't relevant at all, there is no reason not to benchwarp because there are no additional checks. In case 2 you can enemy or background pogo out, but the walk back is also short
